### ISSUE TITLE
Some attributes does not work i.e android:popupLayout="@xml/keyboard_popup"

### ISSUE THREAD

**Issue by adil9d** [hijamoya/KeyboardView#2]
What I have to do? In deprecated this attribute work perfectly but in this module it crashed and give null object reference Can you guide me?

**Comment by hijamoya** [comment]
@adil9d try using `app:popupLayout=`

**Comment by adil9d** [comment]
Thanks I solved that Firstly I was not using style. Secondly in my custom popLayout the keyboardView was android default. 3rd in csutom layout my id was different from you KeyboadView id. These three mistake were there. By the way Thanks alot.

**Comment by adil9d** [comment]
<item name="keyPreviewLayout">@android:layout/keyboard_key_preview</item>
 <item name="popupLayout">@android:layout/keyboard_popup_keyboard</item>
 Above two lines show appt error I committed these lines now App working fine.

**Comment by adil9d** [comment]
Thanks Alot
